[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mateo_st"
# Also update version in init!
version = "1.1.4"
authors = [
    {name = "Bram Vanroy", email = "bramvanroy@hotmail.com"},
]
maintainers = [
    {name = "Bram Vanroy", email = "bramvanroy@hotmail.com"},
]
description = "An interface for machine translation evaluation"
readme = "README.md"
keywords = ["machine translation", "machine translation evaluation", "bleu", "comet"]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Text Processing",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

requires-python = ">=3.10"
# When adding metrics from git, make sure to add the right commit in metrics_constants.py for the metric's 'version'
dependencies = [
    "accelerate==0.16.0",
    "altair==4.2.2",
    "beautifulsoup4==4.11.2",
    "bert-score==0.3.13",
    "datasets==2.10.0",
    "evaluate @ git+https://github.com/huggingface/evaluate.git@af3c30561d840b83e54fc5f7150ea58046d6af69",
    "Levenshtein",
    "optimum==1.7.1",
    "pandas==2.0.1",
    "plotly==5.13.0",
    # Include ja/ko tokenization options
    "sacrebleu[ja,ko]==2.3.1",
    "scikit-learn==1.2.1",
    "sentencepiece==0.1.97",
    "streamlit==1.22.0",
    "tensorflow==2.11.0",
    "torch==1.13.1",
    "transformers==4.28.1",
    "unbabel-comet @ git+https://github.com/Unbabel/COMET.git@04f30d0ab85a4daca4e672286f6cf985de6d02a8",
    "XlsxWriter==3.0.8",
    "BLEURT @ git+https://github.com/google-research/bleurt.git@cebe7e6f996b40910cfaa520a63db47807e3bf5c"
]

[project.urls]
homepage = "https://github.com/BramVanroy/mateo-demo"
documentation = "https://github.com/BramVanroy/mateo-demo"
repository = "https://github.com/BramVanroy/mateo-demo.git"

[project.optional-dependencies]
dev = ["flake8", "black", "isort", "pytest-playwright"]

# TOOLS
[tool.setuptools]
include-package-data = true
license-files = ['LICEN[CS]E*']

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 119
target-version = ["py310", "py311"]

[tool.isort]
profile = "black"
ensure_newline_before_comments = true
line_length = 119
default_section = "FIRSTPARTY"
known_first_party = "mateo_st"
lines_after_imports = 2

# flake8 is in setup.cfg as it does not support toml:
# https://github.com/PyCQA/flake8/issues/234
